### ISSUE TITLE
repository 'https://github.com/Youki/gcp-getting-started-lab-jp/' not found error

### ISSUE THREAD

**Issue by MAMEDEKA** [GoogleCloudPlatform/gcp-getting-started-lab-jp#13]
**Is your feature request related to a problem? Please describe.**
I'm trying   [Google Cloud Hands-on](https://inthecloud.withgoogle.com/gcp-online-handson/index.html).
When I open Google [auto ML hands-on](bit.ly/automl_v1) link, I meet follow error message.
I can't start Hand-son.

> Welcome to Cloud Shell! Type "help" to get started.
> To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
> age_kawakita@cloudshell:~$ cloudshell_open --repo_url "https://github.com/Youki/gcp-getting-started-lab-jp" --page "editor" --tutorial "machine_learning/cloud_ai_building_blocks/cloud_automl_tutorial.md"
> Cloning into 'gcp-getting-started-lab-jp-2'...
> Username for 'https://github.com': MAMEDEKA
> Password for 'https://MAMEDEKA@github.com':
> remote: Repository not found.
> fatal: repository 'https://github.com/Youki/gcp-getting-started-lab-jp/' not found
> cd-ing into gcp-getting-started-lab-jp-2
> -bash: cd: gcp-getting-started-lab-jp-2: No such file or directory
> Tutorial file machine_learning/cloud_ai_building_blocks/cloud_automl_tutorial.md does not exist or is not a file`

**Describe the solution you'd like**
[https://github.com/Youki/gcp-getting-started-lab-jp/](https://github.com/Youki/gcp-getting-started-lab-jp/) link is invalid.

I check [https://github.com/GoogleCloudPlatform/gcp-getting-started-lab-jp/](https://github.com/GoogleCloudPlatform/gcp-getting-started-lab-jp/), but I can't find valid links.

**Comment by hasebe** [comment]
@MAMEDEKA 
Thank you for reporting this issue and my apologies to keep you waiting so long.
The link was accidentally updated and it is pointed to the unavailable repository now.
Let me fix this issue soon.
