### ISSUE TITLE
[DevOps] Tutorialの流れを変更

### ISSUE THREAD

**Issue by ktsukago** [GoogleCloudPlatform/gcp-getting-started-lab-jp#5]
**Is your feature request related to a problem? Please describe.**
DevOpsのハンズオンなのに、Deployの実行が後半になりすぎている

**Describe the solution you'd like**
自動デプロイを先にやってからトラブルシュートをやるような流れに変更したい
30 mins
1章でのDevOps概要説明
40 mins
ハンズオン準備編
GKE 入門編
10 mins 
休憩＋終わっていない方のサポート
5 mins 
Wrap up （GKEでアプリが動くことを確認）
30 mins
ビルド・デプロイ自動化編（30 mins）
5 mins
Spinnaker for GCP の Setup起動 （5 mins）
15 mins
トラブルシュート編（15 mins）
10 mins
Clean up 編

**Comment by hasebe** [comment]
Updated the instruction to align your suggestion on PR #17, so let me close this issue at this time.
